# Site settings
title: "COG Submitterator"
email: "andy.sayler@gmail.com"
description: "Web UI for COG"
baseurl: "/"
url: "https://web-cog.cs.colorado.edu"
google_analytics_key: "UA-54269747-1"
cog_api_url: "https://api-cog.cs.colorado.edu"

# Build settings
markdown: kramdown
highlighter: pygments
exclude: [COPYING, README.md, .gitignore, .git]
permalink: / ## disables post output
timezone: America/Denver
lsi: false 

# Serve Settings
port: 4000
host: 0.0.0.0
safe: false
